// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG79kgNiDevtZR9xLWrxTexcP2wZb_Q3A',
    appId: '1:595489089353:web:bdfba6e13327763f78dc98',
    messagingSenderId: '595489089353',
    projectId: 'pollpeonboarding',
    authDomain: 'pollpeonboarding.firebaseapp.com',
    storageBucket: 'pollpeonboarding.appspot.com',
    measurementId: 'G-M2TS8ZR2MW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDopHkc3CLf2ku92qSsxw6vhQDX-Ha4PzE',
    appId: '1:595489089353:android:353657ceee49219678dc98',
    messagingSenderId: '595489089353',
    projectId: 'pollpeonboarding',
    storageBucket: 'pollpeonboarding.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUdTndt-LYOTKLZ-gQ7jFXskljeSHJbp8',
    appId: '1:595489089353:ios:854ae9b1b53591eb78dc98',
    messagingSenderId: '595489089353',
    projectId: 'pollpeonboarding',
    storageBucket: 'pollpeonboarding.appspot.com',
    iosClientId: '595489089353-d114ihhm0nj4ccc06j5gftqccvq9a9hr.apps.googleusercontent.com',
    iosBundleId: 'com.example.pollpe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUdTndt-LYOTKLZ-gQ7jFXskljeSHJbp8',
    appId: '1:595489089353:ios:6bc52658a9f4f93078dc98',
    messagingSenderId: '595489089353',
    projectId: 'pollpeonboarding',
    storageBucket: 'pollpeonboarding.appspot.com',
    iosClientId: '595489089353-gc2ah0uhe3uve4gkr1gblg6q23d6v13k.apps.googleusercontent.com',
    iosBundleId: 'com.example.pollpe.RunnerTests',
  );
}
